### ISSUE TITLE
One install page

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-site#10]
https://argoproj.github.io/argo-site/#/docs;doc=quickstart%2Fintro_argo_quick_start.md should point to https://argoproj.github.io/argo-site/#/get-started/installation

**Comment by cyee88** [comment]
Actually, I want to remove the intro_argo_quick_start.md page entirely. The "get-started/installation" page has all the installation information and we're adding a link to the Tutorial pages at the bottom of this page.

**Comment by rahuldhide** [comment]
@cyee88 this issue is dependent on the other change you are making to remove all crosslinks.

**Comment by alexmt** [comment]
Docs had been updated
