### ISSUE TITLE
https://argoproj.github.io/docs/argo/examples/readme.html outdated

### ISSUE THREAD

**Issue by metanomi** [argoproj/argo-site#12]
Page contains the outdated text:
https://github.com/argoproj/argo/blob/master/pkg/apis/workflow/v1alpha1/types.go

Should be (per https://github.com/argoproj/argo/blob/master/examples/README.md):
https://github.com/argoproj/argo/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go

Assume something missed in ```(cd ../go/src/github.com/argoproj/argo && git pull https://github.com/argoproj/argo.git)```, ```run './scripts/copy-docs.sh'```, ```yarn build && yarn deploy``` steps.

**Comment by crenshaw-dev** [comment]
Looks like this page no longer exists.
