### ISSUE TITLE
Use Cases under Argo Site

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-site#12]
https://argoproj.github.io/argo-site/ Use cases section

There is spelling mistakes and repetition

Please change to

CI Workflows
Run container-native, CI workflows on Kubernetes

Docker-in-Docker (DinD) on Kubernetes
Build Docker Image within a Docker container using DinD

Deploy Stateful and Stateless  apps
Manage persistent volumes and deploy and scale microservices based apps

**Comment by alexmt** [comment]
@mukulikak Do you want to merge 'Stateless App' and 'Stateful App' links into one: 'Deploy Stateful and Stateless apps'? If yes, where 'View Tutorial' link should redirect user? Tutorial 3 for Stateless apps or Tutorial 4 for Stateful apps?

**Comment by alexmt** [comment]
Page had been updated
