### ISSUE TITLE
Add Support/Training Page to Top Level Nav

### ISSUE THREAD

**Issue by caniszczyk** [argoproj/argo-site#141]
Now that Argo has an official certification
https://training.linuxfoundation.org/certification/certified-argo-project-associate-capa/

... it would be great to add a top level "Training" or "Support/Training" nav item similar to 

https://prometheus.io/support-training/

**Comment by caniszczyk** [comment]
friendly ping on where this is

**Comment by huats** [comment]
Please let me know if I can do something to help

**Comment by nate-double-u** [comment]
PR (https://github.com/argoproj/argo-site/pull/142) is open, awaiting review.
