### ISSUE TITLE
Slack join link no longer active.

### ISSUE THREAD

**Issue by edwardgeorge** [argoproj/argo-site#16]
The slack invite on the bottom of the argo workflows page https://argoproj.github.io/argo is no longer active.

Upon clicking on it I am taken to a slack page that says "This invite link is no longer active. Please check with the person who shared it with you to see if there's a new link available."

**Comment by edlee2121** [comment]
Please try this link: https://argoproj.github.io/community/join-slack

**Comment by edwardgeorge** [comment]
yes, that one works for me.

**Comment by alexmt** [comment]
updated slack link on https://argoproj.github.io/argo  as well. Thanks for letting up know @edwardgeorge !
