### ISSUE TITLE
Slack invitation link was expired

### ISSUE THREAD

**Issue by suzuki-shunsuke** [argoproj/argo-site#19]
The invitation link https://argoproj.github.io/community/join-slack was expired.

![image](https://user-images.githubusercontent.com/13323303/74288350-8669a300-4d6f-11ea-845a-5c3153546a90.png)

> This invite link is no longer active.
> Please check with the person who shared it with you to see if there's a new link available.

We have to recreate the link.

https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link

> Workspace Owners and Admins can create a link that anyone can use to join their workspace.
> Invite links can be used by up to 2,000 people.
> You'll need to create a new link if you reach this limit.

**Comment by edlee2121** [comment]
Fixed now. Thank you for reporting.

@alexmt Your commit on Feb 7 inadvertently overwrote the link with an old obsolete link. Where did you copy the link from?
https://github.com/argoproj/argoproj.github.io/commit/0c4a90d63b2ef674750f4fa973b26528ecb2b0a0
