### ISSUE TITLE
Add LF/CNCF Footer (remove Intuit logo at bottom)

### ISSUE THREAD

**Issue by caniszczyk** [argoproj/argo-site#26]
See the Envoy footer as an example: https://www.envoyproxy.io/

https://github.com/cncf/foundation/blob/master/website-guidelines.md

**Comment by alexmt** [comment]
Footer has been updated. @caniszczyk please let me know  if any other changes are required: 

![image](https://user-images.githubusercontent.com/426437/78734182-69c79280-78fc-11ea-8dd1-4e4c6885be7e.png)

**Comment by caniszczyk** [comment]
can you add this text below everything like the envoy site with links to the trademark usage etc?

"2020 © Argo Project Authors. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our Trademark Usage page: https://www.linuxfoundation.org/trademark-usage"

**Comment by alexmt** [comment]
Done. Trademark text is added.

**Comment by caniszczyk** [comment]
thanks!
