### ISSUE TITLE
Running a workflow

### ISSUE THREAD

**Issue by mukulikak** [argoproj/argo-site#9]
https://applatix.atlassian.net/wiki/spaces/ENG/pages/73105409/Argo+Architecture shows the flow for running a workflow. need to add that in architecture section

**Comment by rahuldhide** [comment]
@roofi07 You can get the content from [this page]([https://applatix.atlassian.net/wiki/spaces/ENG/pages/73105409/Argo+Architecture ]). We also need to make following changes-
- Reduce the diagram height
- Add Running a Workflow section below the diagram
- Add Services and Components title above the component list

![architecture](https://user-images.githubusercontent.com/30275450/29898400-679a0baa-8d9a-11e7-961a-0c17e821aad5.png)

**Comment by rahuldhide** [comment]
**# Running a Workflow**
## Argo workflow YAML is submitted to the Argo API Server

- Performs parameter substitution and creates a fully expanded JSON document
- Submits the expanded JSON to ADC

## ADC schedules the workflow

- Decides which job to admit 
- Waits for minimal resources (CPU & memory)  needed to run the workflow 
- Creates a WFE pod to run the workflow
- Monitoris WFE's

## WFE creates pods via AX Mon to run each step in the workflow

- Processes a graph describing the complete set of sequential and parallel steps that should be executed for a workflow 
- Creates pods to execute any step that is currently executable (i.e. it's predecessor steps have completed)
- A workflow with many paraIlel steps could have many pods running at the same time
- Create pods for dynamic fixtures if any
- Reserve static fixtures if any
- Schedule deployments if any
- Restart steps interrupted by minion restarts etc.

For each pod in a workflow step run init and sidecar containers for initialization, log/artifact management, reporting and cleanup.
