### ISSUE TITLE
Add info about ArgoCon 2022 with the URL on argoproj.github.io and docs(?) 

### ISSUE THREAD

**Issue by wojtekidd** [argoproj/argo-site#91]
Let's add some info (text banner? an image banner with the help of CNCF?) about ArgoCon 2022

"ArgoCon 2022 - a vendor-neutral Argo event coming in September 2022 in SF Bay Area. [Find out more!](https://events.linuxfoundation.org/argocon/)"

or something along the line 👆🏼

**Comment by todaywasawesome** [comment]
On it!
